In [3]:
import numpy as np
from math import sin

In [5]:
list_integers = list(range(20, 31, 2)) #setup cannot be decimal values
list_integers
#sin(list_integers) # does not work as sin requires a single number

[20, 22, 24, 26, 28, 30]

In [6]:
list_integers = np.arange(20, 31, 2)
np.sin(list_integers)

array([ 0.91294525, -0.00885131, -0.90557836,  0.76255845,  0.27090579,
       -0.98803162])

In [13]:
np.linspace(20, 30, 11)#11 equally spaced numbers
np.linspace(20, 30, 10)#10 equally spaced numbers
np.linspace(20, 30, 51)#51 equally spaced numbers

array([20. , 20.2, 20.4, 20.6, 20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. ,
       22.2, 22.4, 22.6, 22.8, 23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2,
       24.4, 24.6, 24.8, 25. , 25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4,
       26.6, 26.8, 27. , 27.2, 27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6,
       28.8, 29. , 29.2, 29.4, 29.6, 29.8, 30. ])

Random Integers

In [17]:
import random
x = np.array([random.randint(-10, 10) for i in range(20)])
print(x)

[ 3 -1 -7 -3  5  7 -4  3  9  8  4 -8  5 -8  2 -7  3  1 -6 -7]


Can apply any numpy mathematical function to a numpy array

In [23]:
np.mean(x)
np.exp(x)
np.max(x)
np.argmax(x)
x[8]
x[-1]
x[3:7]

array([-3,  5,  7, -4])

In [28]:
def f(t):
    return np.exp(t) + np.sin(t**2)

In [29]:
f(x)

array([ 2.04976554e+01,  1.20935043e+00, -9.52840771e-01,  4.61905554e-01,
        1.48280807e+02,  1.09567941e+03, -2.69587678e-01,  2.04976554e+01,
        8.10245404e+03,  2.98187801e+03,  5.43102467e+01,  9.20361501e-01,
        1.48280807e+02,  9.20361501e-01,  6.63225360e+00, -9.52840771e-01,
        2.04976554e+01,  3.55975281e+00, -9.89300101e-01, -9.52840771e-01])