In [17]:
import numpy as np
from numpy import linalg as la

2D ARRAY OR MATRICES

In [2]:
A = np.array([[1,2,3],[-4,2,7],[9,10,-11]])
A

array([[  1,   2,   3],
       [ -4,   2,   7],
       [  9,  10, -11]])

Number of values in matrix

In [26]:
A.size

9

Matrix dimension

In [29]:
A.shape

(3, 3)

Reshaping

In [5]:
import random

a = np.array([random.randint(1, 100) for i in range(20)])
a

array([19, 17, 25, 90, 10, 40, 22, 17, 30, 41, 48, 27, 23, 68, 17, 96, 79,
       38, 24, 98])

Reshape Matrix(i.e. Change dimensions)

In [7]:
M = a.reshape(4,5)
M

array([[19, 17, 25, 90, 10],
       [40, 22, 17, 30, 41],
       [48, 27, 23, 68, 17],
       [96, 79, 38, 24, 98]])

In [11]:
N = M.transpose()

Matrix multiplication

In [14]:
#M*N #does not work because * means term by term multiplication, does not khow to multiply the list terms?
M.dot(N)

array([[ 9475,  4669,  8236,  7257],
       [ 4669,  4954,  5642, 10962],
       [ 8236,  5642,  8475, 10913],
       [ 7257, 10962, 10913, 27081]])

In [15]:
M@N #M at the rate N. Another way to multiple M by N

array([[ 9475,  4669,  8236,  7257],
       [ 4669,  4954,  5642, 10962],
       [ 8236,  5642,  8475, 10913],
       [ 7257, 10962, 10913, 27081]])

In [23]:
D = M@N
D

array([[ 9475,  4669,  8236,  7257],
       [ 4669,  4954,  5642, 10962],
       [ 8236,  5642,  8475, 10913],
       [ 7257, 10962, 10913, 27081]])

Other Matrix operations

In [25]:
la.det(D)
#la.det(M) fails, only works for square matrices


7997625773423.907

In [26]:
la.inv(D)

array([[ 2.05650283e-03, -1.88035020e-03, -2.11430410e-03,
         1.06206412e-03],
       [-1.88035020e-03,  8.43278808e-03, -8.31194919e-05,
        -2.87609167e-03],
       [-2.11430410e-03, -8.31194919e-05,  3.02456665e-03,
        -6.18604744e-04],
       [ 1.06206412e-03, -2.87609167e-03, -6.18604744e-04,
         1.16580448e-03]])

In [28]:
la.matrix_rank(D)

4

In [29]:
D.trace()

49985

HIGHER DIMENSIONAL MATRICES

3 Dimensional Matrix

In [30]:
dimension = 3

In [38]:
matrix_1 = np.arange(9).reshape(dimension, dimension)
matrix_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
matrix_2 = np.arange(10, 19).reshape(dimension, dimension)
matrix_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [40]:
matrix_3 = np.arange(20, 29).reshape(dimension, dimension)
matrix_3

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [41]:
three_dimensional_matrix = np.array([matrix_1, matrix_2, matrix_3])
three_dimensional_matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [45]:
matrix_2_second_column = three_dimensional_matrix[1][:,1] #[:,1] = All rows(i.e. :) second column(i.e. index 1)
matrix_2_second_column

14

In [48]:
matrix_2_second_column_second_value = matrix_2_second_column[1]
matrix_2_second_column_second_value

14

matrix_2_second_column_second_value equivalent

In [49]:
three_dimensional_matrix[1,1,1]

14

Other operaions

In [51]:
D.flatten()

array([ 9475,  4669,  8236,  7257,  4669,  4954,  5642, 10962,  8236,
        5642,  8475, 10913,  7257, 10962, 10913, 27081])