In [2]:
import numpy as np

VECTORS

In [3]:
v = np.array([3,-2,4])
w = np.array([5,2.5,3.8])

Term by Term operations

In [ ]:
v+w

array([8. , 0.5, 7.8])

In [13]:
v_scaled_by_2 = 2*v

In [14]:
w_scaled_by_3 = 3*w

In [15]:
v_scaled_by_2 + w_scaled_by_3

array([21. ,  3.5, 19.4])

In [7]:
v*w

array([15. , -5. , 15.2])

Dot product

In [16]:
v.dot(w)

25.2

In [17]:
w.dot(v)

25.2

LINEAR ALGEBRA

In [19]:
from numpy import linalg as la

In [20]:
la.norm(v)

5.385164807134504

In [22]:
np.cross(v,w)

array([-17.6,   8.6,  17.5])

2D ARRAY OR MATRICES

In [25]:
A = np.array([[1,2,3],[-4,2,7],[9,10,-11]])
A

array([[  1,   2,   3],
       [ -4,   2,   7],
       [  9,  10, -11]])

In [26]:
A.size

9

Matrix dimension

In [29]:
A.shape

(3, 3)